engine:
    name: docker
    options:
        volumes: [/Users/jayjeetchakraborty/.ssh:/root/.ssh]
        environment:
            ANSIBLE_HOST_KEY_CHECKING: false
            NODES: 5
            NODE_HARDWARE: m400
