engine:
    name: docker
    options:
        volumes: [/Users/jayjeetchakraborty/.ssh:/root/.ssh]
        environment:
            ANSIBLE_HOST_KEY_CHECKING: false
            NODES: 2
            NODE_HARDWARE: c8220
            NODE_CLUSTER: clemson
            NODE_SLICE_NAME: test-slice
