all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
masters:
  hosts:
    master:
      ansible_host: !!python/unicode '128.110.153.8'
      ansible_user: noobjc
workers:
  hosts:
    worker1:
      ansible_host: !!python/unicode '128.110.152.240'
      ansible_user: noobjc
    worker2:
      ansible_host: !!python/unicode '128.110.152.247'
      ansible_user: noobjc
