all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
masters:
  hosts:
    master:
      ansible_host: 130.127.133.84
      ansible_user: noobjc
workers:
  hosts:
    worker1:
      ansible_host: 130.127.133.61
      ansible_user: noobjc
